version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "rsync -arq /home/node/app/.aws/ /home/node/.aws &&
               rsync -arq /home/node/cache/node_modules/ /home/node/app/node_modules &&
               cp /home/node/cache/package-lock.json /home/node/app/package-lock.json &&
               npm run serve"
    volumes:
      - .:/home/node/app
    user: node
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"
      - "8080:8080"