service: flowroute-messages

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

custom:
  siteName: ${self:service}
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: dist

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: flowroute-messages
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn:
        - StaticSite
      Properties:
        Bucket: !Ref StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: !Join ["", ["arn:aws:s3:::", !Ref StaticSite, "/*"]]
  Outputs:
    StaticSiteURL:
      Description: "Flowroute Messages Website URL"
      Value: !GetAtt [StaticSite, WebsiteURL]
